# Generated by Django 2.2.2 on 2019-06-05 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowedStatus',
        ),
    ]
