# Generated by Django 2.2.2 on 2019-06-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0002_auto_20190605_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='ILike',
            field=models.BooleanField(default=False),
        ),
    ]
