# Generated by Django 2.2.2 on 2019-06-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0004_auto_20190609_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlike',
            name='islike',
            field=models.BooleanField(default=True),
        ),
    ]
