# Generated by Django 2.2.2 on 2019-06-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0006_coments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlike',
            name='islike',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
